(
  ("jose" . ((user-emacs-directory . "~/.config/emacs")
             (server-name . "jose")
            )
  )
  ("doom" . ((user-emacs-directory . "~/.config/doom")
             (server-name . "doom")
             (env . (("DOOMDIR" . "~/.config/doom")))
            )
  )
  ("spacemacs" . ((user-emacs-directory . "~/.config/spacemacs")
                   (server-name . "spacemacs")
                   (env . (("SPACEMACSDIR" . "~/.spacemacs.d")))
                  )
  )
)
