#! /bin/sh

sxhkd &

bspc monitor -d 1 2 3 4 5 6 7 8 9 10

bspc config border_width         2
bspc config window_gap          12
#bspc config top_padding         30
bspc config normal_border_color  "#252525"
bspc config focused_border_color  "#0050B7"
bspc config presel_feedback_color  "#89B8F7"
#bspc config presel_feedback_color  argb:031D1D1D
bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config focus_follows_pointer true


#bspc config external_rules_command ~/.config/bspwm/external_rules
bspc rule -a Chromium desktop='^3' state=tiled
bspc rule -a discord desktop='^4'
#bspc rule -a Gimp desktop='^8' state=floating follow=on
#bspc rule -a mplayer2 state=floating
#bspc rule -a Kupfer.py focus=on
#bspc rule -a Screenkey manage=off

#~/scripts/startup.sh
