#!/bin/sh

#wid="$1"
#class="$2"
#instance="$3"
eval "$4"

tiled_count="$(bspc query -N -d 3 -n '.!hidden.!floating.!fullscreen.window' | wc -l)"
[ "$tiled_count" -ge 1 ] \
    && echo 'state=floating'
