#! /bin/sh

# Autostart
setxkbmap
xmodmap $HOME/.Xmodmap
[ -f $HOME/.xsessionrc ] && source $HOME/.xsessionrc
killall -q sxhkd
sxhkd &
picom --experimental-backends &
xset s off -dpms &

MONITOR1=DP-0

# Configuration 1
bspc monitor $MONITOR1 -d 1 2 3 4 5 6 7 8 9 10
# Configuration 2
#MONITOR2=HDMI-0
#$HOME/.screenlayout/dual_screen.sh;
#bspc monitor $MONITOR1 -d 1 2 3 4 5
#bspc monitor $MONITOR2 -d 6 7 8 9 10

feh --bg-scale ~/Pictures/Wallpapers/city_night_city_coast_179489_3840x2160.jpg
$HOME/.config/polybar/launch.sh &
bsp-layout set ntall 1 -- --master-size 0.4&

bspc config border_width         3
bspc config window_gap           20
bspc config focused_border_color "#7aa2f7"

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc rule -a firefox desktop='^2'
bspc rule -a Screenkey manage=off
bspc rule -a Zathura state=tiled 
bspc rule -a Emacs state=tiled 
bspc rule -a kdenlive desktop='^7'
bspc rule -a obs desktop='^8'
bspc rule -a 'VirtualBox Manager' desktop='^9'
bspc rule -a 'VirtualBox Machine' desktop='^10'
