#! /bin/sh

# Autostart
xmodmap $HOME/.Xmodmap
source $HOME/.xsessionrc
sxhkd &
picom &
caffeine &
xset s off -dpms &
feh --bg-scale $HOME/Pictures/Wallpapers/red_wallpaper.jpeg &
$HOME/.config/polybar/launch.sh &

# Monitor setup
MONITOR=DP-0

bspc monitor $MONITOR -d 1 2 3 4 5 6 7 8 9 10

bspc config border_width         2
bspc config window_gap          20

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a firefox desktop='^2'
bspc rule -a Thunderbird desktop='^3'
bspc rule -a Evince desktop='^5'
bspc rule -a 'VirtualBox Manager' desktop='^9'
bspc rule -a 'VirtualBox Machine' desktop='^10'
bspc rule -a Screenkey manage=off

