#! /bin/sh

# Autostart
xmodmap $HOME/.Xmodmap
source $HOME/.xsessionrc
sxhkd &
picom &
feh --bg-scale $HOME/Pictures/red_wallpaper.jpeg &
$HOME/.config/polybar/launch.sh &

#bspc monitor <monitor-name> -d 1 2 3 4 5 6 7 8 9 10
bspc monitor DP-0 -d 1 2 3 4 5 6 7 8 9 10

bspc config border_width         2
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a firefox desktop='^2'
bspc rule -a Thunderbird desktop='^3'
bspc rule -a Evince desktop='^5'
bspc rule -a Screenkey manage=off

