#!/bin/zsh

CURRENT_DIR=$(pwd)
BASE_NAME=$(basename $CURRENT_DIR)
sed -i "s/export CURRENT_REPORT.*/export CURRENT_REPORT='$BASE_NAME'/g" $HOME/.zshrc
/usr/bin/git --git-dir=$HOME/.cfg/ --work-tree=$HOME add $HOME/.zshrc
/usr/bin/git --git-dir=$HOME/.cfg/ --work-tree=$HOME commit -m "Update weekly_report path."
/usr/bin/git --git-dir=$HOME/.cfg/ --work-tree=$HOME push
source $HOME/.zshrc
